name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --spec cypress/e2e/eve_test.cy.js

      - name: Run Newman tests
        run: |
          npm install -g newman
          newman run API_Tests.postman_collection copy.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: cypress/results


